# Generated by Django 4.2.7 on 2023-12-09 13:51

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        choices=[
                            (blog.models.Author["CHEF"], "C"),
                            (blog.models.Author["ADMINISTRATOR"], "A"),
                            (blog.models.Author["OWNER"], "O"),
                        ],
                        max_length=1,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=20)),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "post",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="")),
                ("loaded", models.DateTimeField(auto_now_add=True)),
                ("preview", models.ImageField(blank=True, upload_to="")),
                (
                    "real",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "db_table": "photo",
            },
        ),
    ]
