# Generated by Django 4.2.7 on 2023-12-11 12:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="real",
            new_name="post",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="preview",
        ),
        migrations.AlterField(
            model_name="photo",
            name="img",
            field=models.ImageField(upload_to=blog.models.Photo._load_to),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(
                choices=[
                    (blog.models.Author["CHEF"], "Chef"),
                    (blog.models.Author["ADMINISTRATOR"], "Admin"),
                    (blog.models.Author["OWNER"], "Owner"),
                ],
                max_length=1,
            ),
        ),
    ]
