# Generated by Django 4.2.7 on 2023-12-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_real_photo_post_remove_photo_preview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_posting",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
